/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compilador;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dell
 */
public class CompiladorFrame extends javax.swing.JFrame {

    /**
     * Creates new form CompiladorFrame
     */ 
    String caminho = "0";
    
    public CompiladorFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abrirArqDialog = new javax.swing.JDialog();
        nomeArqTxtField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        salvarDialog = new javax.swing.JDialog();
        caminhoTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        codigoTxtArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        saidaTxtArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        abrirMenu = new javax.swing.JMenu();
        salvarMenu = new javax.swing.JMenu();
        compilarMenu = new javax.swing.JMenu();

        abrirArqDialog.setTitle("Abrir Arquivo");

        nomeArqTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeArqTxtFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel3.setText("Caminho do arquivo:");

        javax.swing.GroupLayout abrirArqDialogLayout = new javax.swing.GroupLayout(abrirArqDialog.getContentPane());
        abrirArqDialog.getContentPane().setLayout(abrirArqDialogLayout);
        abrirArqDialogLayout.setHorizontalGroup(
            abrirArqDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abrirArqDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abrirArqDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abrirArqDialogLayout.createSequentialGroup()
                        .addComponent(nomeArqTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abrirArqDialogLayout.setVerticalGroup(
            abrirArqDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abrirArqDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abrirArqDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeArqTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        salvarDialog.setTitle("Salvar Arquivo");

        caminhoTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caminhoTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Insira o caminho do arquivo:");

        jButton2.setText("Ok");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout salvarDialogLayout = new javax.swing.GroupLayout(salvarDialog.getContentPane());
        salvarDialog.getContentPane().setLayout(salvarDialogLayout);
        salvarDialogLayout.setHorizontalGroup(
            salvarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salvarDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(salvarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salvarDialogLayout.createSequentialGroup()
                        .addComponent(caminhoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel4))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        salvarDialogLayout.setVerticalGroup(
            salvarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salvarDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(salvarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caminhoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        codigoTxtArea.setColumns(20);
        codigoTxtArea.setRows(5);
        jScrollPane1.setViewportView(codigoTxtArea);

        jLabel1.setText("Saída");

        jLabel2.setText("Código-fonte");

        saidaTxtArea.setEditable(false);
        saidaTxtArea.setColumns(20);
        saidaTxtArea.setRows(5);
        jScrollPane2.setViewportView(saidaTxtArea);

        abrirMenu.setText("Abrir");
        abrirMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(abrirMenu);

        salvarMenu.setText("Salvar");
        salvarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salvarMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(salvarMenu);

        compilarMenu.setText("Compilar");
        compilarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compilarMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(compilarMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeArqTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeArqTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeArqTxtFieldActionPerformed

    private void abrirMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirMenuMouseClicked
        // TODO add your handling code here:
        abrirArqDialog.setVisible(true);
        abrirArqDialog.setSize(350, 150);
    }//GEN-LAST:event_abrirMenuMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         int i = 1;
        FileInputStream stream;
        try {
            caminho = nomeArqTxtField.getText();
            stream = new FileInputStream(caminho);
            InputStreamReader reader = new InputStreamReader(stream);
            BufferedReader br = new BufferedReader(reader);
        
            String linha = br.readLine();
            String txt = "";
            while(linha != null) {
                if(i<10){
                    txt += i +"   |   "+ linha+"\n";
                }else{
                    txt += i +" |   "+ linha+"\n";
                }
            
                linha = br.readLine();
                i++;
            }
            codigoTxtArea.setText(txt);
            abrirArqDialog.setVisible(false);
            //C:\Users\Dell\Desktop\teste.txt
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CompiladorFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CompiladorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void salvarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salvarMenuMouseClicked
        // TODO add your handling code here:
        salvarDialog.setVisible(true);
        salvarDialog.setSize(350, 150);
    }//GEN-LAST:event_salvarMenuMouseClicked

    private void caminhoTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caminhoTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caminhoTxtFieldActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
                FileWriter arq;
        try {
            arq = new FileWriter(caminhoTxtField.getText());
            PrintWriter gravarArq = new PrintWriter(arq);

            gravarArq.printf(codigoTxtArea.getText());
            arq.close();
            salvarDialog.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(CompiladorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void compilarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compilarMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_compilarMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompiladorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompiladorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompiladorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompiladorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompiladorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog abrirArqDialog;
    private javax.swing.JMenu abrirMenu;
    private javax.swing.JTextField caminhoTxtField;
    private javax.swing.JTextArea codigoTxtArea;
    private javax.swing.JMenu compilarMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomeArqTxtField;
    private javax.swing.JTextArea saidaTxtArea;
    private javax.swing.JDialog salvarDialog;
    private javax.swing.JMenu salvarMenu;
    // End of variables declaration//GEN-END:variables
}
